# Generated by Django 2.1.7 on 2019-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleName', models.CharField(help_text='Rule Name', max_length=13)),
                ('campaign', models.CharField(help_text='campaign Name', max_length=13)),
                ('schedule', models.TimeField(help_text='Schedule Time', max_length=13)),
                ('action', models.CharField(help_text='Action', max_length=13)),
                ('status', models.CharField(help_text='Status', max_length=13)),
            ],
        ),
    ]
